modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/sekwah41/SekCDevTools/issues"
license="All rights reserved"
[[mods]]
modId="sekcdevtools"
version="${file.jarVersion}"
displayName="Sekwah Core Dev Tools"
authors="Sekwah41"
description='''
Just a couple of edits to make my life a bit easier or fun while doing dev stuff.
'''

[[dependencies.sekcdevtools]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

# https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html
[[dependencies.sekcdevtools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,)"
    ordering="NONE"
    side="BOTH"
